const information = {
  'e1': 'Punkt',
  'e2': 'shoulder',
  'e3': 'aperture',
  'e4': 'Stamm',
  'e5': 'spur',
  'e6': 'Schattenachse',
  'e7': 'Schulter',
  'e8': 'ascender',
  'e9': 'descender',
  'e10': 'Auslauf',
  'e11': 'Querstrich',
  'e12': 'Bauch',
  'e13': 'terminal',
  'e14': 'terminal',
  'e15': 'Schleife',
  'e16': 'Steg/Hals',
  'e17': 'ear',
  'e18': 'tail',
  'e19': 'Querstrich',
  'e20': 'apex',
  'e21': 'vertex',
  'e22': 'overhang',
  'e23': 'apex',
  'e24': 'apex',
  'e25': 'beak',
  'e26': 'joint',
  'e27': 'bracket',
  'e28': 'bracket',
  'e29': 'Querstrich',
  'e30': 'arc',
  'e31': 'zweiseitige Serifen',
  'e32': 'zweiseitige Serifen',
  'e33': 'Bein',
  'e34': 'counter (closed)',
  'e35': 'Aufstrich/Haarstrich',
  'e36': 'crotch',
  'e37': 'Bein',
  'e38': 'Arm',
  'e39': 'bowl',
  'e40': 'eye',
  'e41': 'counter (open)',
  'e42': 'Arm',
  'e43': 'Bogen',
  'e44': 'serif',
  'e45': 'Ligatur',
  'e46': 'beak',
  'e47': 'spine',
  'e48': 'head serif',
  'e49': 'head serif'
}
